### PR TITLE
Package

### PR DESCRIPTION
**Pull request by lasamlai**
1. Changing plld into swipl-ld in Makefile
2. Adding test to Makefile
3. Changing enum_fann_print_mode_switch to enum_fann_mode_switch in fann_swi.h
4. Fixing example.pl
5. Changing something that looks like a bug in plfann.pl
6. Creating swipl package (adding pack.pl, moving plfann.pl to prolog).

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Sent a message to Degski.  Looks ok to me, but it is his package after all.

**Comment by JanWielemaker** [comment]
Degski is ok with this.  He suggests you might be willing to take control of the package.  Does that interest you?

**Comment by lasamlai** [comment]
Sure!

**Comment by JanWielemaker** [comment]
Great!  I guess you want write access to the repo?

**Comment by lasamlai** [comment]
Yes.

**Comment by lasamlai** [comment]
Thanks.

**Comment by JanWielemaker** [comment]
Hope it will just get nicer!

**Pull request merged**
